set nocompatible "vi非互換モード
set backupdir=/tmp
set autoread

"#######################
" 表示系
"#######################
set number "行番号表示
set showmode "モード表示
set title "編集中のファイル名を表示
set ruler "ルーラーの表示
set showcmd "入力中のコマンドをステータスに表示する
set showmatch "括弧入力時の対応する括弧を表示
set laststatus=2 "ステータスラインを常に表示

"set list              " 不可視文字表示
"set listchars=tab:>.,trail:_,extends:>,precedes:< " 不可視文字の表示形式
set display=uhex      " 印字不可能文字を16進数で表示

" 全角スペースの表示
highlight ZenkakuSpace cterm=underline ctermfg=lightblue guibg=darkgray
match ZenkakuSpace /　/

" カーソル行をハイライト
"set cursorline

" コマンド実行中は再描画しない
set lazyredraw
" 高速ターミナル接続を行う
set ttyfast
" マウスはビジュアルモードでのみ有効になる
set mouse=v

"#######################
" プログラミングヘルプ系
"#######################
set smartindent "オートインデント
" tab関連
" ファイルを開いた際に、前回終了時の行で起動
autocmd BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal g`\"" | endif

"#######################
" 検索系
"#######################
set ignorecase "検索文字列が小文字の場合は大文字小文字を区別なく検索する
set smartcase "検索文字列に大文字が含まれている場合は区別して検索する
set wrapscan "検索時に最後まで行ったら最初に戻る
set hlsearch " 検索結果をハイライト
" 検索結果のハイライトをesc連打で消す
nmap <Esc><Esc> :nohlsearch<CR><Esc>

set backspace=indent,eol,start

autocmd BufNewFile,BufRead *.tt set filetype=php

" auto remove tail's space/tab
autocmd BufWritePre * :%s/\s\+$//e
autocmd BufWritePre * :%s/\t\+$//e

"#######################
" vundle
"#######################
"$ git clone http://github.com/gmarik/vundle.git ~/.vim/vundle.git
set nocompatible               " be iMproved
filetype off                   " required!
set rtp+=~/.vim/bundle/vundle.git/
call vundle#rc()
" let Vundle manage Vundle
" required!

" My Bundles
Bundle 'thinca/vim-localrc'

"syntastic options
" tips : how to close Errors Window -> :lclose
execute pathogen#infect()
Bundle 'scrooloose/syntastic'
let g:syntastic_check_on_open=1
let g:syntastic_enable_perl_checker = 1
"let g:syntastic_aggregate_errors = 1
let g:syntastic_perl_checkers = ['perl', 'podchecker']
let g:syntastic_mode_map = {
      \  'mode': 'active',
      \ 'active_filetypes': ['ruby', 'javascript', 'perl'],
      \ 'passive_filetypes': []
      \ }
"let g:syntastic_javascript_checker = 'jslint'
let g:syntastic_warning_symbol = '⚠'
let g:syntastic_auto_jump = 2

filetype plugin indent on     " required!
"let $JS_CMD='node'
"
Bundle 'altercation/vim-colors-solarized'
syntax enable
"set background=dark
colorscheme solarized
